### ISSUE TITLE
Web Services - 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by Aymkdn** [s-KaiNet/node-sp-auth#30]
Hi,

So, I've been able to connect to our Sharepoint Online using [Addin method](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication).

If I query some REST API services (like `/_api/web/lists/getbytitle('Test')/items`), then it works.

However, if I use it to access to a web service (e.g. `/_vti_bin/lists.asmx`), then it doesn't work and returns a **401 UNAUTHORIZED**.
Example: 
```javascript
const spauth = require('node-sp-auth');
const request = require('request-promise');
const credentials = require('../credentials_online');

spauth
.getAuth('https://tenant.sharepoint.com/sites/dev/', credentials)
.then(data => {
  let headers = data.headers;
  headers['SOAPAction'] = 'http://schemas.microsoft.com/sharepoint/soap/GetList';
  headers["Content-Type"]="text/xml; charset=utf-8";

  request.post({
    url: "https://tenant.sharepoint.com/sites/dev/_vti_bin/lists.asmx",
    headers: headers,
    rejectUnauthorized: false,
    body:'<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetList xmlns="http://schemas.microsoft.com/sharepoint/soap/"><listName>Test</listName></GetList></soap:Body></soap:Envelope>'
  }).then(response => {
    console.log(response);
  });
});
```

My *Addin auth only App* has site collection permissions : 
```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

I searched on the web and that might be related to an auth cookie that is missing ? Maybe the `FedAuth` ? Is there anyway to generate it?

If I use the auth method `{ondemand:true}` then it works.
BTW, how long does the FedAuth cookie persist with this method?

Thanks

**Comment by s-KaiNet** [comment]
> However, if I use it to access to a web service (e.g. /_vti_bin/lists.asmx), then it doesn't work and returns a 401 UNAUTHORIZED.   

Actually this is expected, because add-in auth uses OAuth and bearer tokens for authentication. Only modern REST API supports it. That's why  all `asmx` services will throw an error.     

So for asmx you need FedAuth cookie, which is generated only by username\password auth, which, in turn, doesn't work for you because of PingIdentity. FedAuth is also generated by `ondemand` auth as you mentioned. However I'm not sure about the lifetime of that cookie, I think a few days. Sometimes cookie has expiration information, sometimes not. If not set, `node-sp-auth` stores it for 24hours.         

The last thing you can do is to try adfs credentials once again. Use below auth config:   
```javascript
{
  username: 'username in format johnsmith@contoso-corp.com',
  password: 'password',
  relyingParty: 'urn:federation:MicrosoftOnline',
  adfsUrl: 'your adfs url, normally the host part of url, where you enter your domain credentials, like https://intranet.adfs.com'
}
```   
To be honest I don't have any more ideas. The issue is PingIdentity, but I don't know what it is, thus making difficult to investigate how to workaround it in node-sp-auth.

**Comment by Aymkdn** [comment]
The ADFS method didn't work. I tried different things, but it failed all the time :-( If I discover something, I'll let you know.

Thank you for your quick & useful support!

**Comment by dlandry99** [comment]
I am getting the same type of issues 401 Unauthorized intermittently on my Project Online Rest Requests.  It will work fine for months and then something is changed on the tenant and bam 401 errors.  Has anyone experienced this problem and if so do you have some direction.  I know its not the code because again it has been working for months with no issue.

**Comment by s-KaiNet** [comment]
Which kind of auth do you use?

**Comment by pholpar** [comment]
@dlandry99 
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs
Azure Access Control (ACS), a service of Azure Active Directory (Azure AD), has been retired on November 7, 2018. This retirement does not impact the SharePoint Add-in model, which uses the https://accounts.accesscontrol.windows.net hostname (which is not impacted by this retirement). For more information, see Impact of Azure Access Control retirement for SharePoint Add-ins. **For new tenants, apps using an ACS app-only access token is disabled by default.** We recommend using the Azure AD app-only model which is modern and more secure. But **you can change the behavior by running ‘set-spotenant -DisableCustomAppAuthentication $false'** (needs the latest SharePoint admin PowerShell).

More details:
https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/
