### ISSUE TITLE
node-sp-auth browser environment

### ISSUE THREAD

**Issue by cverhelst** [s-KaiNet/node-sp-auth#32]
Hi Sergei,

First of all, congrats on this library!

I've come upon your library today and I was wondering if there was a reason it's so heavily dependend on nodejs server-side components?

I'm trying to create a client side office outlook add-in (it's a browser environment) and I'm trying to setup a connection to the company's on-prem SharePoint using your library for authentication together with sp-pnp-js and having some difficulty doing this because of the server side dependencies.

Is there an alternative more suited for my situation or a way to grab just specific functionality from your library?

**Comment by s-KaiNet** [comment]
Hi Cameron, thank you!   

It's simply not possible to implement `node-sp-auth` for browser, because techniques, used for authentication inside `node-sp-auth` are not suitable for browser for below reasons:   
 - CORS
 - no implicit flow in SharePoint add-ins OAuth  

In other words you can't use it in browser, because it will never work.   

For browser you should use different methods\libraries\techniques. If you environment is SharePoint online, then you can safely go ahead with adal-js, however that's not your case.    

To help you, can you please clarify which authentication does your on-premise SharePoint use?

**Comment by s-KaiNet** [comment]
BTW issue `#1` for you, is that on-premise SharePoint deson't support CORS. I assume your add-in running on domain, other than SharePoint, which automatically makes all calls to SharePoint suffer from CORS restrictions.

**Comment by cverhelst** [comment]
Yeah, I was afraid we may have to end up at this conclusion. Altough, is it a SP2013 on-prem limitation or rather a JS "browser environment" limitation?

To clarify my use case:

- SharePoint 2013 hosts a bunch of site collections with folder structures
- People at the administration department need to frequently upload files from Outlook mail into specific folders in this structure
- Our goal is to end up with an Outlook Add-In which allows them to
  * Search the whole SP 2013 farm for sites
  * Browse through the folder structure
  * Select a location for uploading the mail/attachments

I had thought the last bit would be the most difficult. I've come close to the idea of just doing it all server side and calling the webservice to do all the interaction with SP for me.

**Comment by cverhelst** [comment]
I'm still learning this but apparently I'll end up having node.js on Azure which hosts the whole Outlook Add-In. I'm a bit baffled about why it's a "browser environment", because actually it's a server.

It may end up having to do with my local dev tool chain that comes out of the box with the Outlook Add-In project. I'm hoping that once I get it up on Azure I'll find that actually I do have a proper node environment.

**Comment by cverhelst** [comment]
As I'm thinking this through, I realise I may not be using that Outlook Add-In correctly, since you have JS served on the HTML page, and a server side component (I think). When doing stuff on the server side I shouln't have any trouble using your library as-is.

Thanks!

**Comment by s-KaiNet** [comment]
Yes, it looks like you messed up a bit where is a server and a browser component in regards to Outlook add-in.    
Usually that's a server hosted somewhere and web front-end which is shown in Outlook.   
As you have a server, I would recommend you to go ahead with C# approach (if you are familiar with it), because .NET today has better integration with SharePoint-related stuff.

**Comment by s-KaiNet** [comment]
You also mentioned `sp-pnp-js`, I recommend you to switch to [PnPjs](https://github.com/pnp/pnp), because original [`sp-pnp-js`](https://github.com/SharePoint/PnP-JS-Core) will be deprecated in less than 5 months.   
`PnPjs` is production ready and has the same feature parity, main development currently occurs in `PnPjs`.

**Comment by cverhelst** [comment]
Cool! Thanks for the headsup, hadn't noticed they were restructuring xO.

I do prefer C# for these kind of things, but I wasn't aware you could do an Outlook addin in C#? I mean, I suppose theoretically you can but I hadn't seen a template for it yet. The one in VS is acually a JS project.

I could move all the SP interaction to a C# backend, seems like the better option in this case actually.

Thanks for thinking with me and sorry for proposing such a silly thing xD!

**Comment by s-KaiNet** [comment]
Ah it's absolutely ok, glad you clarified things. I'm closing the issue for now, however feel free to reopen or ask further questions, if any.

**Comment by cverhelst** [comment]
For anyone finding this because of my use case:

I ended up using .net webservices to connect to SP wich also allowed me to use the EWS managed API which is waaaay more functional if you need to do full email exports, as I had to. Thanks to Sergei to get me on the server-side track more quickly than I was planning to myself which saved me a lot of headaches and time!
