### ISSUE TITLE
Switch request and request-promise to node-fetch

### ISSUE THREAD

**Issue by estruyf** [s-KaiNet/node-sp-auth#81]
As the `request` dependency has been deprecated, it might be useful to switch to another library like `node-fetch`.

**Comment by s-KaiNet** [comment]
Actually it's on the way - you can check out [this branch](https://github.com/s-KaiNet/node-sp-auth/tree/new-sp-auth) and install `node-sp-auth@beta`. There is also `sp-request@beta` and `spsave@beta` as well.   
The main differences are   
- [got](https://github.com/sindresorhus/got) instead of `request`, because got has closest feature parity
- no bluebird anymore, only native promises.    

If you use `sp-request`, there are some breaking changes, you can read more [here](https://github.com/s-KaiNet/sp-request/blob/new-sp-request/UpgradeTo3x.md)   

It's stable and everything works just fine. I'm planning to release it soon. If you have any suggestions you're welcome :)

**Comment by estruyf** [comment]
Great to know!

**Comment by s-KaiNet** [comment]
`node-sp-auth@3.x` was released with `got` support instead of deprecated `request`.
